// Generated by CoffeeScript 1.6.2
(function() {
  (function() {
    var cdiv, detail, link, links, _i, _len, _results;

    links = document.querySelectorAll("#links a");
    detail = document.getElementById("detail");
    cdiv = null;
    _results = [];
    for (_i = 0, _len = links.length; _i < _len; _i++) {
      link = links[_i];
      _results.push(link.onclick = function() {
        var showdiv, _j, _len1;

        cdiv = document.querySelector(this.dataset["selector"]);
        if (!cdiv.classList.contains("focus")) {
          for (_j = 0, _len1 = links.length; _j < _len1; _j++) {
            link = links[_j];
            link.classList.remove("focus");
          }
          this.classList.add("focus");
          showdiv = function() {
            var div, _k, _len2, _ref;

            _ref = document.querySelectorAll("#detail div");
            for (_k = 0, _len2 = _ref.length; _k < _len2; _k++) {
              div = _ref[_k];
              div.classList.remove("focus");
            }
            cdiv.classList.add("focus");
            return detail.classList.add("show");
          };
          if (detail.classList.contains("show")) {
            detail.classList.remove("show");
            return setTimeout(showdiv, 500);
          } else {
            return showdiv.call();
          }
        }
      });
    }
    return _results;
  })();

}).call(this);

/*
//@ sourceMappingURL=links.map
*/
